In [18]:
from dotenv import load_dotenv
from openai import OpenAI
import os

load_dotenv()
client = OpenAI()

In [19]:
response = client.embeddings.create(
    model = 'text-embedding-3-small',
    input=['Hello World', '안녕하세요']
)

response

CreateEmbeddingResponse(data=[Embedding(embedding=[0.004802703857421875, -0.054718017578125, 0.0455322265625, 0.031524658203125, -0.0283355712890625, -0.0296783447265625, -0.03143310546875, 0.0316162109375, -0.01421356201171875, 0.01534271240234375, 0.006114959716796875, -0.029693603515625, -0.0310516357421875, -0.0224456787109375, 0.0308380126953125, 0.0246429443359375, -0.056671142578125, 0.01373291015625, 0.0190277099609375, 0.0316162109375, 0.044952392578125, -0.0031719207763671875, -0.01451873779296875, -0.017120361328125, 0.0220947265625, -0.01282501220703125, -0.037841796875, 0.00812530517578125, 0.0139007568359375, -0.0462646484375, 0.0287017822265625, -0.048309326171875, -0.01175689697265625, 0.0189361572265625, -0.0011968612670898438, -0.0008835792541503906, 0.016876220703125, -0.0060577392578125, 0.01262664794921875, -0.021392822265625, 0.028533935546875, -0.025665283203125, 0.0013523101806640625, 0.050262451171875, -0.02813720703125, 0.031005859375, -0.07373046875, 0.026458740234375, 0.04278564453125, 0.044586181640625, -0.0305633544921875, -6.204843521118164e-05, 0.0269775390625, 0.0849609375, -0.037689208984375, -0.0516357421875, 0.020416259765625, 0.03790283203125, -0.036956787109375, 0.0299835205078125, 0.0122222900390625, 0.0102691650390625, 0.0007038116455078125, 0.0184326171875, 0.0212860107421875, -0.01468658447265625, -0.017578125, 0.01175689697265625, -0.0089111328125, 0.056488037109375, 0.00806427001953125, 0.037322998046875, -0.0162811279296875, 0.0007648468017578125, -0.0589599609375, -0.01221466064453125, -0.0457763671875, -0.0170135498046875, -0.0189208984375, -0.05865478515625, -0.035980224609375, 0.03271484375, -0.056732177734375, -0.03778076171875, -0.0192718505859375, 0.017547607421875, -0.04345703125, -0.01337432861328125, -0.01464080810546875, -0.01386260986328125, 6.854534149169922e-05, -0.00545501708984375, -0.0287933349609375, 0.038177490234375, 0.0204925537109375, 0.0034008026123046875, 0.00634765625, 0.054931640625, 0.0628662109375, -0.02557373046875, 0.0260162353515625, -0.034759521484375, 0.0318603515625, -0.0316162109375, 0.00896453857421875, 0.00301361083984375, -0.01035308837890625, -0.051544189453125, -0.041412353515625, 0.029510498046875, -0.104248046875, -0.04302978515625, 0.0122222900390625, -0.00803375244140625, 1.9252300262451172e-05, 0.0183868408203125, 0.07598876953125, -0.04193115234375, 0.033782958984375, -0.05816650390625, 0.028564453125, -0.0169830322265625, -0.01904296875, -0.0648193359375, -0.0438232421875, -0.02154541015625, -0.023681640625, 0.04290771484375, -0.034912109375, -0.010467529296875, 0.036590576171875, 0.02569580078125, 0.013427734375, -0.033660888671875, -0.041656494140625, 0.00795745849609375, -0.03271484375, -0.01128387451171875, -0.031890869140625, 0.0433349609375, 0.039306640625, -0.031982421875, 0.006633758544921875, -0.024658203125, -0.006053924560546875, -0.035247802734375, -0.01381683349609375, 0.03350830078125, -0.0142974853515625, -0.0015735626220703125, 0.042449951171875, 0.0504150390625, -0.052642822265625, 0.002758026123046875, 0.028167724609375, -0.0186614990234375, 0.0498046875, -0.046112060546875, -0.00897979736328125, 0.0236968994140625, 0.037506103515625, 0.027801513671875, -0.037139892578125, -0.0020198822021484375, -0.0009369850158691406, 0.01151275634765625, 0.018707275390625, 0.00103759765625, -0.052978515625, -0.006404876708984375, 0.0150604248046875, 0.0095672607421875, -0.0268707275390625, -0.06634521484375, -0.0131988525390625, 0.0164794921875, 0.0020751953125, -0.0457763671875, 0.005279541015625, -0.026275634765625, 0.04754638671875, 0.0587158203125, 0.0205841064453125, 0.0021457672119140625, -0.02606201171875, -0.010650634765625, -0.005680084228515625, -0.0037994384765625, -0.004974365234375, -0.00018537044525146484, -0.042022705078125, 0.04876708984375, 0.028228759765625, 0.004322052001953125, -0.0009441375732421875, -0.040802001953125, 0.069580078125, 0.01209259033203125, -0.00875091552734375, 0.01934814453125, -0.01171875, 0.011474609375, -0.0174560546875, -0.030670166015625, -0.02703857421875, -0.031646728515625, 0.01019287109375, 0.06005859375, -0.01318359375, -0.03472900390625, 0.08123779296875, -0.0161895751953125, -0.0175933837890625, -0.019439697265625, -0.048370361328125, -0.0167999267578125, 0.01198577880859375, 0.022125244140625, 0.0017824172973632812, -0.041351318359375, -0.032867431640625, 0.063720703125, 0.06842041015625, 0.0187835693359375, 0.023651123046875, 0.00717926025390625, 0.0083465576171875, -0.032867431640625, 0.05487060546875, 0.013824462890625, 0.0213775634765625, 0.0185546875, 0.01123046875, -0.043060302734375, 0.0015010833740234375, -0.03076171875, 0.046051025390625, -0.016510009765625, -0.00555419921875, 0.0024776458740234375, -0.06549072265625, -0.0120697021484375, 0.0114288330078125, 0.032562255859375, 0.0360107421875, -0.005218505859375, -0.034637451171875, -0.0391845703125, 0.036102294921875, 0.0198974609375, 0.03277587890625, 0.022857666015625, -0.01317596435546875, 0.0040283203125, 0.0303192138671875, -0.0009121894836425781, -0.0111846923828125, 0.00928497314453125, 0.043182373046875, -0.020751953125, -0.0367431640625, -0.04620361328125, -0.01155853271484375, -0.0311737060546875, -0.0197296142578125, -0.02386474609375, 0.01380157470703125, 0.0016679763793945312, -0.01898193359375, -0.0213775634765625, 0.039093017578125, -0.00022721290588378906, 0.0653076171875, -0.02581787109375, -0.004283905029296875, -0.00884246826171875, -0.0118560791015625, -0.00034117698669433594, -0.035491943359375, 0.028076171875, -0.0192718505859375, -0.0060272216796875, -0.00702667236328125, 0.0631103515625, -0.04327392578125, 0.002460479736328125, 0.021636962890625, -0.00809478759765625, -0.00565338134765625, -0.0004394054412841797, 0.03350830078125, 0.044281005859375, 0.0316162109375, -0.0130462646484375, 0.0311126708984375, 0.01555633544921875, 0.0228271484375, -0.0205535888671875, 0.04547119140625, -0.037750244140625, 0.059234619140625, -0.0120391845703125, 0.010345458984375, 0.0298614501953125, -0.0117034912109375, 0.0330810546875, 0.0236968994140625, -0.04473876953125, 0.0594482421875, 0.01242828369140625, -0.0218505859375, -0.0026569366455078125, 0.048614501953125, -0.030853271484375, -0.0258026123046875, -0.0694580078125, -0.0252838134765625, -0.034759521484375, 0.000736236572265625, -0.0290069580078125, 0.028564453125, -0.055694580078125, -0.0125579833984375, 0.01357269287109375, 0.02545166015625, -0.020904541015625, 0.05511474609375, 0.0234375, 0.0119476318359375, -0.0082855224609375, -0.0033664703369140625, -0.0288238525390625, -0.0079498291015625, -0.006130218505859375, 0.0008664131164550781, -0.0078887939453125, -0.0418701171875, 0.0419921875, -0.0003457069396972656, 0.033721923828125, -0.0028228759765625, -0.046783447265625, 0.0015811920166015625, -0.02252197265625, 0.010711669921875, -0.01389312744140625, 0.0382080078125, -0.0428466796875, 0.009246826171875, 0.0015506744384765625, 0.01212310791015625, 0.00543212890625, -0.0027523040771484375, -0.005397796630859375, -0.0133819580078125, -0.01132965087890625, 0.044769287109375, -0.0203399658203125, 0.00490570068359375, 0.0372314453125, -0.006023406982421875, -0.0116119384765625, 0.0036106109619140625, 0.00421142578125, 0.04119873046875, 0.02545166015625, -0.0212554931640625, -0.055419921875, 6.4373016357421875e-06, 0.030242919921875, 0.002346038818359375, -0.0067291259765625, 0.00666046142578125, -0.00713348388671875, -0.0229034423828125, -0.0360107421875, 0.01036834716796875, -0.007778167724609375, 0.03271484375, -0.0163116455078125, 0.01088714599609375, 0.01397705078125, -0.005283355712890625, -0.011444091796875, 0.005115509033203125, -0.006839752197265625, 0.0311126708984375, 0.0205535888671875, 0.0197906494140625, -0.01296234130859375, 0.01800537109375, -0.01525115966796875, 0.017913818359375, 0.011474609375, 0.0026302337646484375, -0.03057861328125, 0.00916290283203125, 0.01052093505859375, 0.0012807846069335938, -0.058563232421875, 0.060943603515625, -0.043182373046875, 0.020111083984375, 0.02325439453125, -0.06414794921875, -0.06768798828125, -0.0197906494140625, 0.05438232421875, -0.008087158203125, -0.0380859375, 0.00711822509765625, -0.04498291015625, 0.0287628173828125, 0.020172119140625, -0.01739501953125, -0.00920867919921875, -0.007495880126953125, -0.051849365234375, 0.0288543701171875, 0.02996826171875, -0.00597381591796875, 0.0281524658203125, -0.042694091796875, 0.0266265869140625, -0.0097198486328125, 0.049285888671875, 0.04949951171875, -0.017547607421875, -0.0205078125, -0.095458984375, -0.0186614990234375, -0.0016880035400390625, -0.0203857421875, 0.0124969482421875, -0.00476837158203125, -0.033416748046875, 0.003154754638671875, -0.002178192138671875, 0.048583984375, 0.023406982421875, 0.006191253662109375, 0.01329803466796875, -0.018310546875, -0.0101776123046875, -0.0032196044921875, -0.042236328125, 0.0001850128173828125, -0.007747650146484375, -0.03277587890625, -0.01123809814453125, 0.01125335693359375, -0.06109619140625, 0.0191802978515625, 0.0021076202392578125, -0.00946044921875, 0.004062652587890625, 0.01800537109375, 0.00447845458984375, -0.0021266937255859375, 0.0186920166015625, 0.016571044921875, 0.00014472007751464844, -0.0643310546875, 0.04327392578125, 0.038818359375, -0.01419830322265625, -0.01136016845703125, -0.0020427703857421875, -0.01189422607421875, -0.0504150390625, -0.009613037109375, 0.003177642822265625, 0.03656005859375, -0.01898193359375, -0.003520965576171875, -0.0037441253662109375, -0.0287322998046875, 0.019012451171875, -0.0180206298828125, -0.0021800994873046875, 0.045989990234375, 0.00013816356658935547, 0.0147552490234375, -0.0050048828125, -0.00403594970703125, 0.0836181640625, -0.0716552734375, -0.0128021240234375, -0.0316162109375, -0.0262908935546875, -0.04364013671875, 0.0458984375, 0.044921875, -0.021209716796875, -0.000896453857421875, -0.04364013671875, 0.02117919921875, -0.0205078125, 0.003498077392578125, -0.035003662109375, -0.00205230712890625, -0.0179595947265625, -0.01216888427734375, 0.0172271728515625, 0.07415771484375, -0.0207366943359375, -0.0345458984375, -0.0273895263671875, 0.0225830078125, -0.0231170654296875, -0.05145263671875, 0.003955841064453125, 0.01273345947265625, -0.01407623291015625, -0.00423431396484375, -0.013458251953125, -0.00867462158203125, 0.02349853515625, -0.00418853759765625, -0.031768798828125, -0.004230499267578125, 0.032196044921875, -0.018280029296875, -0.03271484375, 0.021087646484375, 0.0020694732666015625, -0.0225677490234375, 0.0035495758056640625, -0.01459503173828125, 0.0225677490234375, 0.01439666748046875, -0.0079193115234375, 0.032928466796875, 0.001262664794921875, -0.03216552734375, -0.003192901611328125, -0.0029506683349609375, 0.01049041748046875, 0.002696990966796875, 0.0013828277587890625, 0.0208892822265625, 0.009368896484375, 0.025848388671875, 0.01049041748046875, -0.01084136962890625, 0.0059356689453125, 0.024261474609375, 0.028350830078125, 0.0072021484375, 0.0286102294921875, -0.0109405517578125, -0.02142333984375, -0.0208740234375, -0.0129547119140625, 0.032501220703125, -0.00919342041015625, -0.0188446044921875, -0.002559661865234375, -0.00010699033737182617, 0.059356689453125, 0.004459381103515625, -0.0109405517578125, 0.0191192626953125, 0.0200347900390625, -0.007419586181640625, 0.01467132568359375, -0.01336669921875, -0.0271148681640625, -0.032318115234375, -0.0234832763671875, -0.0254669189453125, -0.021484375, -0.01470184326171875, -0.038330078125, 0.0011396408081054688, 0.0012969970703125, 0.0098724365234375, 0.017974853515625, 0.0265655517578125, -0.00970458984375, -0.0247039794921875, -0.0158538818359375, -0.023529052734375, 0.032440185546875, -0.057861328125, 0.04742431640625, 0.0173492431640625, 0.01177978515625, 0.0389404296875, -0.0276031494140625, 0.02972412109375, 0.0253448486328125, 0.037506103515625, 0.016571044921875, -0.002002716064453125, -0.007244110107421875, -0.0009627342224121094, 0.0127716064453125, -0.041534423828125, 0.041259765625, 0.01873779296875, 0.01220703125, -0.0020542144775390625, -0.0299835205078125, 0.015869140625, -0.005855560302734375, -0.0271759033203125, -0.01383209228515625, -0.0026607513427734375, -0.05316162109375, -0.041961669921875, 0.041229248046875, 0.0031795501708984375, -0.04608154296875, -0.0222930908203125, 0.037200927734375, -0.0277557373046875, -0.005615234375, 0.01580810546875, -0.025543212890625, -0.0052947998046875, -0.036376953125, 0.00867462158203125, 0.039459228515625, 0.0019817352294921875, 0.0196075439453125, -0.0279541015625, -0.0178985595703125, -0.009613037109375, 0.005199432373046875, 0.0279388427734375, 0.015655517578125, 0.036895751953125, -0.02008056640625, -0.007251739501953125, -0.0015087127685546875, 0.0153045654296875, 0.00727081298828125, -0.0029430389404296875, -0.0272216796875, 0.0244903564453125, -0.01477813720703125, 0.0173187255859375, -0.009368896484375, 0.059967041015625, 0.0168609619140625, 0.01432037353515625, 0.0235137939453125, -0.0009236335754394531, -0.018218994140625, 0.0262603759765625, 0.01297760009765625, 0.0253143310546875, -0.0004305839538574219, 0.0293731689453125, -0.00858306884765625, -0.047607421875, -0.0155181884765625, -0.0224151611328125, 0.0227203369140625, -0.0265960693359375, 0.032623291015625, -0.02801513671875, -0.0180206298828125, -0.006420135498046875, -0.0019483566284179688, -0.017425537109375, 0.0256500244140625, 0.01245880126953125, -0.01288604736328125, -0.00795745849609375, -0.00373077392578125, 0.050933837890625, -0.01361083984375, 0.04034423828125, -0.00939178466796875, -0.0016641616821289062, -0.0277862548828125, 0.00446319580078125, -0.0169677734375, 0.005222320556640625, 0.03192138671875, -0.043182373046875, -0.017791748046875, 0.0153045654296875, 0.0263824462890625, 0.025390625, 0.0258941650390625, 0.00287628173828125, -0.00197601318359375, -0.0255584716796875, -0.0231170654296875, 0.0304412841796875, 0.017852783203125, 0.01218414306640625, -0.00783538818359375, 0.029296875, 0.0048065185546875, -0.01168060302734375, -0.061309814453125, 0.027679443359375, -0.007640838623046875, -0.0165863037109375, 0.016021728515625, 0.00457763671875, -0.006229400634765625, -0.02740478515625, 0.0283203125, 0.036773681640625, 0.0176849365234375, -0.02587890625, -0.0240936279296875, -0.00231170654296875, -0.00891876220703125, -0.039093017578125, -0.006999969482421875, -0.010040283203125, -0.042083740234375, -0.0012941360473632812, -0.010101318359375, -0.043121337890625, 0.015167236328125, -0.01311492919921875, 0.00960540771484375, -0.017913818359375, -0.0118865966796875, 0.019744873046875, -0.0178680419921875, 0.035919189453125, 0.0089569091796875, 0.0134124755859375, -0.0037384033203125, 0.0241546630859375, 0.003814697265625, 0.0030994415283203125, -0.005367279052734375, -0.04833984375, -0.00366973876953125, 0.0016841888427734375, -0.04583740234375, -0.0175628662109375, 0.00571441650390625, 0.01200103759765625, 0.033294677734375, -0.0254974365234375, -0.0238037109375, 0.011077880859375, 0.01262664794921875, -0.00833892822265625, -0.01519775390625, -0.0036106109619140625, 0.0140228271484375, -0.024932861328125, 0.00275421142578125, 0.015655517578125, -0.030914306640625, 0.0206451416015625, 0.0142059326171875, -0.0021038055419921875, 0.030426025390625, -0.01500701904296875, 0.045745849609375, -0.0011339187622070312, 0.03448486328125, -0.00618743896484375, 0.002353668212890625, 0.007610321044921875, 0.007076263427734375, -0.003490447998046875, 0.0023822784423828125, 0.0321044921875, 0.005504608154296875, 0.019439697265625, 0.01123046875, 0.001422882080078125, -0.01027679443359375, -0.0287933349609375, 0.0034084320068359375, -0.048004150390625, -0.0173797607421875, -0.01708984375, 0.00849151611328125, -0.0251617431640625, -0.019012451171875, 0.0051116943359375, -0.0203704833984375, 0.0185394287109375, 0.0019702911376953125, 0.005458831787109375, -0.03924560546875, -0.0299835205078125, -0.024871826171875, -0.00325775146484375, -0.031463623046875, 0.0142822265625, 0.050537109375, 0.003509521484375, -0.0238800048828125, 0.014892578125, -0.01702880859375, -0.00531005859375, -0.038177490234375, 0.02191162109375, 0.0205078125, 0.007049560546875, -0.0011110305786132812, -0.0181427001953125, 0.006725311279296875, -0.00925445556640625, -0.003620147705078125, 0.0018148422241210938, 0.049713134765625, -0.0168609619140625, 0.0240478515625, 0.0043487548828125, -0.025634765625, 0.016326904296875, -0.018707275390625, 0.00949859619140625, 0.018707275390625, 0.0006957054138183594, -0.00038814544677734375, -0.034820556640625, -0.02789306640625, 0.070068359375, 0.033355712890625, -0.0041961669921875, 0.0300140380859375, 0.0382080078125, -0.018280029296875, -0.0004429817199707031, -9.119510650634766e-06, 0.000560760498046875, -0.01197052001953125, 0.0016965866088867188, 0.03778076171875, 0.0135345458984375, -0.03106689453125, -0.0189666748046875, -0.0237884521484375, -0.013153076171875, -0.01348114013671875, -0.01029205322265625, -0.01117706298828125, 0.06488037109375, -0.01155853271484375, 0.00714874267578125, 0.0042877197265625, -0.007755279541015625, 0.00518798828125, -0.01702880859375, -0.048248291015625, 0.031585693359375, -0.021148681640625, -0.02386474609375, 0.016448974609375, -0.0202789306640625, -0.0223236083984375, -0.018310546875, -0.033233642578125, -0.00926971435546875, 0.0328369140625, 0.0177154541015625, 0.038543701171875, 0.01119232177734375, -0.011932373046875, 0.005191802978515625, 0.0168914794921875, 0.0469970703125, 0.034454345703125, 0.00948333740234375, 0.0185699462890625, -0.01397705078125, -0.01482391357421875, 0.022674560546875, 0.0269775390625, -0.06298828125, 0.020599365234375, -0.00618743896484375, -0.022430419921875, 0.02056884765625, 0.0082244873046875, -0.00839996337890625, -0.0198822021484375, -0.0177459716796875, -0.0260162353515625, 0.00843048095703125, 0.01401519775390625, 0.0208282470703125, -0.0167388916015625, 0.0119476318359375, -0.0004963874816894531, 0.0037994384765625, -0.010162353515625, 0.00457763671875, -0.018829345703125, -0.006214141845703125, 0.04901123046875, 0.00862884521484375, 0.0106048583984375, -0.0038909912109375, -0.0258941650390625, -0.00519561767578125, 0.021820068359375, 0.006870269775390625, 0.0032634735107421875, -0.01213836669921875, -0.01245880126953125, 0.00598907470703125, -0.0015287399291992188, -0.00033545494079589844, -0.058868408203125, 0.0156402587890625, 0.0079803466796875, 0.054443359375, 0.0214691162109375, 0.0012712478637695312, 0.02362060546875, 0.0305023193359375, 0.0171661376953125, -0.00543975830078125, -0.0362548828125, -0.036956787109375, 0.033172607421875, -0.01172637939453125, 0.01531982421875, -0.054779052734375, 0.060791015625, 0.0174407958984375, -0.006229400634765625, 0.027587890625, 0.01090240478515625, -0.0278167724609375, 0.01983642578125, 0.0113067626953125, 0.00738525390625, -0.032073974609375, 0.02813720703125, -0.0148468017578125, -0.0287933349609375, -0.02337646484375, 0.0272979736328125, 0.01849365234375, 0.009765625, 0.06219482421875, 0.0244293212890625, -0.0005054473876953125, -0.01263427734375, 0.00013017654418945312, -0.004161834716796875, -0.013397216796875, -0.020111083984375, 0.00348663330078125, -0.0123291015625, -0.031463623046875, 0.010284423828125, 0.060791015625, -0.0079498291015625, -0.01264190673828125, 0.002193450927734375, -0.01284027099609375, -0.015655517578125, -0.024688720703125, 0.0005660057067871094, 0.01152801513671875, 0.006664276123046875, -0.036834716796875, -0.01126861572265625, 0.0120849609375, -0.012725830078125, -0.00986480712890625, -0.0006008148193359375, 0.020904541015625, 0.02349853515625, -0.01165771484375, -0.00408172607421875, -0.00420379638671875, 0.0174560546875, 0.0304412841796875, 0.0058746337890625, 0.02947998046875, -0.011810302734375, 0.007965087890625, -0.004055023193359375, -0.0197296142578125, -0.0034503936767578125, 0.011138916015625, 0.0123138427734375, -0.0129547119140625, -0.0066375732421875, 0.01233673095703125, 0.000934600830078125, -0.05987548828125, 0.024169921875, 0.02899169921875, -0.0009994506

In [20]:
len(response.data[0].embedding)

1536

In [21]:
emb_vec0 = response.data[0].embedding
emb_vec1 = response.data[1].embedding

len(emb_vec0), len(emb_vec1)

(1536, 1536)

In [22]:
def text_to_embedding(texts, model='text-embedding-3-small'):
    texts = [text.replace('\n', ' ') for text in texts]
    response = client.embeddings.create(model=model, input=texts)

    return [data.embedding for data in response.data]

vecs = text_to_embedding(['Hello World', '안녕하세요'])

In [23]:
len(vecs[0]), len(vecs[1])

(1536, 1536)

In [24]:
import pandas as pd

review_df = pd.read_csv('fine_food_reviews_1k.csv', index_col=0)
print(review_df.info())
print(review_df.head())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Time       1000 non-null   int64
 1   ProductId  1000 non-null   str
 2   UserId     1000 non-null   str
 3   Score      1000 non-null   int64
 4   Summary    1000 non-null   str
 5   Text       1000 non-null   str
dtypes: int64(2), str(4)
memory usage: 450.7 KB
None
         Time   ProductId          UserId  Score  \
0  1351123200  B003XPF9BO  A3R7JR3FMEBXQB      5
1  1351123200  B003JK537S  A3JBPC3WFUT5ZP      1
2  1351123200  B000JMBE7M   AQX1N6A51QOKG      4
3  1351123200  B004AHGBX4  A2UY46X0OSNVUQ      3
4  1351123200  B001BORBHO  A1AFOYZ9HSM2CZ      5

                                             Summary  \
0  where does one  start...and stop... with a tre...
1                                  Arrived in pieces
2          It isn't blanc mange, but isn't bad . . .
3        These also have SALT and it's not sea salt.
4                             Happy with the product

                                                Text
0  Wanted to save some to bring to my Chicago fam...
1  Not pleased at all. When I opened the box, mos...
2  I'm not sure that custard is really custard wi...
3  I like the fact that you can see what you're g...
4  My dog was suffering with itchy skin.  He had ...

In [25]:
review_df = review_df[['Summary', 'Text']]
review_df['Content'] = 'Title: ' + review_df['Summary'].str.strip() + '; Content: ' + review_df['Text'].str.strip()

In [26]:
review_df

,Summary,Text,Content
0,where does one start...and stop... with a tre...,Wanted to save some to bring to my Chicago fam...,Title: where does one start...and stop... wit...
1,Arrived in pieces,"Not pleased at all. When I opened the box, mos...",Title: Arrived in pieces; Content: Not pleased...
2,"It isn't blanc mange, but isn't bad . . .",I'm not sure that custard is really custard wi...,"Title: It isn't blanc mange, but isn't bad . ...."
3,These also have SALT and it's not sea salt.,I like the fact that you can see what you're g...,Title: These also have SALT and it's not sea s...
4,Happy with the product,My dog was suffering with itchy skin. He had ...,Title: Happy with the product; Content: My dog...
...,...,...,...
995,Delicious!,I have ordered these raisins multiple times. ...,Title: Delicious!; Content: I have ordered the...
996,Good Training Treat,My dog will come in from outside when I am tra...,Title: Good Training Treat; Content: My dog wi...
997,Jamica Me Crazy Coffee,Wolfgang Puck's Jamaica Me Crazy is that wonde...,Title: Jamica Me Crazy Coffee; Content: Wolfga...
998,Party Peanuts,Great product for the price. Mix with the Asia...,Title: Party Peanuts; Content: Great product f...
999,I love Maui Coffee!,My first experience with Maui Coffee was bring...,Title: I love Maui Coffee!; Content: My first ...

In [27]:
review_df['embedding'] = text_to_embedding(review_df['Content'].tolist())
review_df.head()

,Summary,Text,Content,embedding
0,where does one start...and stop... with a tre...,Wanted to save some to bring to my Chicago fam...,Title: where does one start...and stop... wit...,"[0.036651611328125, -0.023193359375, -0.030471..."
1,Arrived in pieces,"Not pleased at all. When I opened the box, mos...",Title: Arrived in pieces; Content: Not pleased...,"[0.01140594482421875, 0.0343017578125, -0.0411..."
2,"It isn't blanc mange, but isn't bad . . .",I'm not sure that custard is really custard wi...,"Title: It isn't blanc mange, but isn't bad . ....","[0.0032253265380859375, 0.01265716552734375, -..."
3,These also have SALT and it's not sea salt.,I like the fact that you can see what you're g...,Title: These also have SALT and it's not sea s...,"[-0.0028896331787109375, 0.01462554931640625, ..."
4,Happy with the product,My dog was suffering with itchy skin. He had ...,Title: Happy with the product; Content: My dog...,"[0.01204681396484375, -0.0560302734375, 0.0167..."

In [28]:
embed_df = review_df['embedding'].to_frame('embedding')
embed_df.index = review_df['Content']
embed_df

                                                                                            embedding
Content
Title: where does one  start...and stop... with...  [0.036651611328125, -0.023193359375, -0.030471...
Title: Arrived in pieces; Content: Not pleased ...  [0.01140594482421875, 0.0343017578125, -0.0411...
Title: It isn't blanc mange, but isn't bad . . ...  [0.0032253265380859375, 0.01265716552734375, -...
Title: These also have SALT and it's not sea sa...  [-0.0028896331787109375, 0.01462554931640625, ...
Title: Happy with the product; Content: My dog ...  [0.01204681396484375, -0.0560302734375, 0.0167...
...                                                                                               ...
Title: Delicious!; Content: I have ordered thes...  [0.016448974609375, -0.039154052734375, -0.026...
Title: Good Training Treat; Content: My dog wil...  [-0.0230255126953125, -0.0139007568359375, 0.0...
Title: Jamica Me Crazy Coffee; Content: Wolfgan...  [-0.029632568359375, -0.045745849609375, -0.02...
Title: Party Peanuts; Content: Great product fo...  [0.0010709762573242188, -0.0225982666015625, -...
Title: I love Maui Coffee!; Content: My first e...  [0.0192108154296875, -0.019317626953125, -0.03...

[1000 rows x 1 columns]

In [29]:
from sklearn.metrics.pairwise import cosine_similarity

def review_vector_search(query, embed_df=embed_df, top_n=5):
    query_emb = text_to_embedding([query])

    df = embed_df.copy()
    df['cos_sim'] = df['embedding'].apply(lambda emb: cosine_similarity([emb], query_emb)[0, 0])

    df = df.sort_values('cos_sim', ascending=False).head()
    df = df.reset_index()
    df = df[['Content', 'cos_sim']]

    return df

pd.set_option('display.max_colwidth', None)
review_vector_search('delicious fruit')

,Content,cos_sim
0,"Title: Delicious!; Content: For anyone who says ""I don't like fruitcake"" or anyone who's never had fruitcake and wonders what all the fuss is about, try this. (As long as you're not allergic to tree nuts or any other ingredient.) It's chock-a-block with nuts and moist fruit. I will definitely be buying more.",0.649448
1,"Title: Delicious .; Content: These plums are sweet and juicy, and the aroma is like perfume. And it doesn't hurt that they are good for you, too.",0.612282
2,"Title: Delicious!; Content: Wonderful! Deep, rich, pure black raspberry syrup! Absolutely delicious on waffles, cheesecake, ice cream, yogurt, drinks, etc. Thrilled to see that there are at least some berry syrup makers who do not feel the need to ""sour"" the flavor of perfect berry products with citric acid!",0.599917
3,"Title: These are Delicious!; Content: Great taste, right price, fabulous snack! It is the only fruit I can get my little one to eat and I can't keep my high school son out of them either. They are great pick-me-ups on the way to my daughter's soccer practice or before my early morning run. And best of all, Amazon ships these right to my door every month. No more finding the right store who carries them. I just set up the automatic recurring shipment once and it works like a charm!",0.591969
4,Title: Delicious!; Content: I have ordered these raisins multiple times. They are always great and arrive timely. I can't go back to store bought chocolate covered raisins now! Love this product.,0.502419

In [30]:
review_vector_search('best coffee')

,Content,cos_sim
0,"Title: Best coffee ever!; Content: In my opinion this is the best coffee ever! I've been drinking coffee for 50 plus years and this is what I serve to myself and friends. However, I wish I could find this grind in a pound size, so I could make a full pot rather than just a single cup.",0.612534
1,"Title: Great Coffee; Content: I have a coffee maker that grinds my coffee beans. It's hard to find whole bean decafinated coffee. When I find it in the brand that I like, I am excited. Seattle's Best is my favorite.",0.610797
2,"Title: Better than you-know-who's coffee...; Content: So my wife is a latte freak, and nursing, so decaf is the approved type. After the Senseo left the market, I struggled and found the <a href=""http://www.amazon.com/gp/product/B0047BIWSK"">Aerobie AeroPress Coffee and Espresso Maker</a> which is like a French Press for the 21st century. After getting our recipe figured out, my wife, who's been buying Venti Decaf Latte's at $4 a pop almost daily for years now declares that Seattle's best Level 3 Decaf in her home-made Latte is the best coffee she can get. We've tried other bands, and this is her favorite, hands down!",0.605585
3,"Title: BEST cup of coffee I've ever had!; Content: I thought I'd splurge and try this coffee. It costs much more than other decaf K-Cup options. But I hoped that meant it was better coffee. It IS better coffee. I've never had a better cup of coffee than this. It is excellent when compared to any other decaf or regular coffee I've tried.<br /><br />If you like BOLD, FLAVORFUL decaf coffee try this coffee and you'll really like it.",0.603422
4,"Title: BEST cup of coffee I've ever had!; Content: I thought I'd splurge and try this coffee. It costs much more than other decaf K-Cup options. But I hoped that meant it was better coffee. It IS better coffee. I've never had a better cup of coffee than this. It is excellent when compared to any other decaf or regular coffee I've tried.<br /><br />If you like BOLD, FLAVORFUL decaf coffee try this coffee and you'll really like it.",0.603387